### ISSUE TITLE
Network security protocols support

### ISSUE THREAD

**Issue by dmat93** [kr1stj0n/pep-dna#1]
Hi all,
for research purposes I was studying your product. I have some questions for you: 

(?) how did you plan to manage secure protocols, like for example HTTPS connections, out of the RINA/ICN context?
(?) does the PEP-DNA support the connection to (public) web-servers (e.g., search engine, social networks, etc)?

Regards.

**Comment by kr1stj0n** [comment]
Hi !

We do not support encrypted traffic yet, but we are planning to investigate more on this in the very near future. For now, PEP-DNA can establish a connection with public web-servers **ONLY** if the TCP header is not encrypted.

This is on of the shortcomings of many PEPs. AFAIK, SatERN handles HTTPS traffic.
You can check some more examples of PEPs in the Related Work section of the paper [1].

-------
[1]. https://ieeexplore.ieee.org/document/9651953
