### ISSUE TITLE
Clarify publications section and add DOI

### ISSUE THREAD

**Issue by joergdeutschmann-i7** [kr1stj0n/pep-dna#2]
Thanks for your work on PEP-DNA and the very interesting papers!

I believe the "Publications" section in the README.md could be made clearer and benefit from some further details, e.g.,

Documents and papers [Link to https://github.com/kr1stj0n/pep-dna/tree/main/pepdna/papers]:
- 29th International Conference on Network Protocols (IEEE ICNP 2021) [Link to icnp-nipaa.pdf]
The talk in the NIPAA'21 Workshop is available here [Link to Youtube].
Please use this DOI [Link to DOI] to cite our work.
- 12th International Conference on Network of the Future (NoF 2021) [Link to demo-nof211.pdf]
A short demo paper.
- Technical report [Link to ciko_welzl_teymoori-pepdna.pdf]
An extended version.

**Comment by kr1stj0n** [comment]
Done! Thank you for the feedback!
